// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace flights.Entity
{
    [Index(nameof(RegisterationNumber), Name = "IX_airlines_RegisterationNumber")]
    public partial class airline
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public string Phone { get; set; }
        public int RegisterationNumber { get; set; }

        [ForeignKey(nameof(RegisterationNumber))]
        [InverseProperty(nameof(airplane.airlines))]
        public virtual airplane RegisterationNumberNavigation { get; set; }
    }
}