// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace flights.Entity
{
    [Index(nameof(FlightNumber), Name = "IX_airplanes_FlightNumber1")]
    public partial class airplane
    {
        public airplane()
        {
            airlines = new HashSet<airline>();
        }

        [Key]
        public int RegisterationNumber { get; set; }
        public int TotalSeat { get; set; }
        [Required]
        public string ModelNumber { get; set; }
        public int FlightNumber { get; set; }

        [ForeignKey(nameof(FlightNumber))]
        [InverseProperty(nameof(flight.airplanes))]
        public virtual flight FlightNumberNavigation { get; set; }
        [InverseProperty(nameof(airline.RegisterationNumberNavigation))]
        public virtual ICollection<airline> airlines { get; set; }
    }
}