// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace flights.Entity
{
    [Keyless]
    public partial class AspNetUserToken
    {
        [Required]
        [StringLength(450)]
        public string UserId { get; set; }
        [Required]
        [StringLength(128)]
        public string LoginProvider { get; set; }
        [Required]
        [StringLength(128)]
        public string Name { get; set; }
        public string Value { get; set; }

        [ForeignKey(nameof(UserId))]
        public virtual AspNetUser User { get; set; }
    }
}