// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace flights.Entity
{
    public partial class country
    {
        public country()
        {
            flights = new HashSet<flight>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [Column(TypeName = "image")]
        public byte[] Image { get; set; }
        public string description { get; set; }

        [InverseProperty(nameof(flight.Country))]
        public virtual ICollection<flight> flights { get; set; }
    }
}