// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace flights.Entity
{
    [Index(nameof(FlightNumber), Name = "IX_tickets_FlightNumber1")]
    [Index(nameof(UserID), Name = "IX_tickets_UserID")]
    public partial class ticket
    {
        [Key]
        public int Id { get; set; }
        public int NoOfSeats { get; set; }
        [Required]
        public string CheckStatus { get; set; }
        [Required]
        public string UserID { get; set; }
        public int FlightNumber { get; set; }

        [ForeignKey(nameof(FlightNumber))]
        [InverseProperty(nameof(flight.tickets))]
        public virtual flight FlightNumberNavigation { get; set; }
        [ForeignKey(nameof(UserID))]
        [InverseProperty(nameof(AspNetUser.tickets))]
        public virtual AspNetUser User { get; set; }
    }
}